// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/password-tokens/:codigo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/password-tokens/[codigo].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/password-tokens/[codigo].post').default>>>>
    }
    '/api/auth/reset': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/reset.post').default>>>>
    }
    '/api/buses/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buses/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buses/[id].put').default>>>>
    }
    '/api/buses/estados': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buses/estados.get').default>>>>
    }
    '/api/buses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buses/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buses/index.post').default>>>>
    }
    '/api/conductor': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conductor/index.get').default>>>>
    }
    '/api/conductor/turnos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conductor/turnos/index.get').default>>>>
    }
    '/api/incidentes/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidentes/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidentes/[id].put').default>>>>
    }
    '/api/incidentes/:id/estado': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidentes/[id]/estado.put').default>>>>
    }
    '/api/incidentes/catalogos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidentes/catalogos.get').default>>>>
    }
    '/api/incidentes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidentes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidentes/index.post').default>>>>
    }
    '/api/mantenimientos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mantenimientos/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mantenimientos/[id].put').default>>>>
    }
    '/api/mantenimientos/catalogos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mantenimientos/catalogos.get').default>>>>
    }
    '/api/mantenimientos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mantenimientos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mantenimientos/index.post').default>>>>
    }
    '/api/mecanicos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mecanicos/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mecanicos/[id].put').default>>>>
    }
    '/api/mecanicos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mecanicos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mecanicos/index.post').default>>>>
    }
    '/api/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/roles/index.get').default>>>>
    }
    '/api/talleres/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talleres/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talleres/[id].put').default>>>>
    }
    '/api/talleres/catalogos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talleres/catalogos.get').default>>>>
    }
    '/api/talleres': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talleres/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talleres/index.post').default>>>>
    }
    '/api/turnos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/turnos/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/turnos/[id].put').default>>>>
    }
    '/api/turnos/catalogos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/turnos/catalogos.get').default>>>>
    }
    '/api/turnos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/turnos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/turnos/index.post').default>>>>
    }
    '/api/usuarios/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/usuarios/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/usuarios/[id].put').default>>>>
    }
    '/api/usuarios': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/usuarios/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/usuarios/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}